/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 条件に合うバリアフリー飲食店を推薦する */
        post: operations["createRecommendations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RecommendationRequest: {
            /**
             * @description 行きたいエリア。デモでは福岡市内を指定する。
             * @example 福岡市中央区
             */
            area: string;
            /**
             * @description 希望する料理ジャンル。未指定でもよい。
             * @example イタリアン
             */
            cuisine?: string;
            /**
             * @description 車椅子の最大横幅（cm）。入口・通路を通れるかの判定に用いる。
             * @example 63
             */
            wheelchair_width_cm: number;
            /**
             * @description エージェントに伝える自由形式の要望。
             * @example 入口に段差がなく、トイレも使いやすい店がよい
             */
            prompt?: string;
            /**
             * @description 返す店舗数。
             * @default 5
             * @example 5
             */
            limit?: number;
        };
        RecommendationResponse: {
            /** @description 推薦順位順の店舗一覧。候補がない場合は空配列。 */
            recommendations: components["schemas"]["RestaurantRecommendation"][];
        };
        RestaurantRecommendation: {
            /** @description 推薦順位。 */
            rank: number;
            /** @description Google Placesのplace ID。 */
            place_id: string;
            /** @description 店舗名。 */
            name: string;
            /** @description 店舗住所。 */
            address: string;
            location: components["schemas"]["Location"];
            /**
             * Format: uri
             * @description Google Mapsで店舗を開くURL。
             */
            maps_url: string;
            accessibility: components["schemas"]["AccessibilityAssessment"];
            /** @description 希望条件に照らして推薦する理由。 */
            recommendation_reason: string;
        };
        Location: {
            latitude: number;
            longitude: number;
        };
        AccessibilityAssessment: {
            /**
             * @description 入店可否の見立て。フロントエンドが○・△・✕へ表示変換する。
             * @enum {string}
             */
            status: "accessible" | "uncertain" | "not_accessible";
            /**
             * @description 判定の確からしさ。
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** @description レビュー、写真、アクセシビリティ属性などから得た判定根拠。 */
            reasons: components["schemas"]["AssessmentReason"][];
        };
        AssessmentReason: {
            /**
             * @description 判定した観点。
             * @example entrance
             */
            condition: string;
            /**
             * @description 根拠が示す判定結果。
             * @enum {string}
             */
            result: "supported" | "unsupported" | "unknown";
            /** @description 根拠の要約。 */
            evidence: string;
        };
        ValidationError: {
            /** @constant */
            code: "VALIDATION_ERROR";
            /** @description エラーの概要。 */
            message: string;
            /** @description 項目ごとの入力エラー。 */
            fields: components["schemas"]["FieldError"][];
        };
        FieldError: {
            /** @description エラーになったリクエスト項目名。 */
            field: string;
            /** @enum {string} */
            code: "REQUIRED" | "INVALID_VALUE";
            /** @description 項目ごとのエラー説明。 */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description 推薦結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description 必須項目の不足または入力値の不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description Content-Type が application/json ではない */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description サーバー内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
