steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, --tag, '${_REGION}-docker.pkg.dev/$PROJECT_ID/michibiki/video:$BUILD_ID', .]
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/michibiki/video:$BUILD_ID'
substitutions:
  _REGION: asia-northeast1
options:
  logging: CLOUD_LOGGING_ONLY
